In [1]:
import numpy as np
import pandas as pd

In [4]:
pd.read_csv('zoo.csv', delimiter = ',')

      animal  uniq_id  water_need
0   elephant     1001         500
1   elephant     1002         600
2   elephant     1003         550
3      tiger     1004         300
4      tiger     1005         320
5      tiger     1006         330
6      tiger     1007         290
7      tiger     1008         310
8      zebra     1009         200
9      zebra     1010         220
10     zebra     1011         240
11     zebra     1012         230
12     zebra     1013         220
13     zebra     1014         100
14     zebra     1015          80
15      lion     1016         420
16      lion     1017         600
17      lion     1018         500
18      lion     1019         390
19  kangaroo     1020         410
20  kangaroo     1021         430
21  kangaroo     1022         410

In [17]:
url = 'http://46.101.230.157/dilan/pandas_tutorial_read.csv'
column_names = ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic']
article_read = pd.read_csv(url, delimiter = ';', names = column_names)

article_read

              my_datetime event    country     user_id   source          topic
0     2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1     2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2     2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3     2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4     2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America
5     2018-01-01 00:05:42  read  country_6  2458151266   Reddit  North America
6     2018-01-01 00:06:06  read  country_2  2458151267   Reddit         Europe
7     2018-01-01 00:06:15  read  country_6  2458151268  AdWords         Europe
8     2018-01-01 00:07:21  read  country_7  2458151269  AdWords  North America
9     2018-01-01 00:07:29  read  country_5  2458151270   Reddit  North America
10    2018-01-01 00:07:57  read  country_5  2458151271  AdWords           Asia
11    2018-01-01 00:08:57  read  country_7  2458151272      SEO      Australia
12    2018-01-01 00:09:11  read  country_5  2458151273   Reddit           Asia
13    2018-01-01 00:09:29  read  country_2  2458151274   Reddit         Europe
14    2018-01-01 00:11:06  read  country_7  2458151275   Reddit         Africa
15    2018-01-01 00:11:22  read  country_7  2458151276      SEO  North America
16    2018-01-01 00:13:05  read  country_8  2458151277      SEO  North America
17    2018-01-01 00:13:06  read  country_2  2458151278   Reddit           Asia
18    2018-01-01 00:13:39  read  country_4  2458151279      SEO  North America
19    2018-01-01 00:14:53  read  country_2  2458151280   Reddit           Asia
20    2018-01-01 00:15:44  read  country_2  2458151281   Reddit           Asia
21    2018-01-01 00:15:50  read  country_7  2458151282   Reddit         Africa
22    2018-01-01 00:17:15  read  country_2  2458151283  AdWords         Europe
23    2018-01-01 00:17:31  read  country_2  2458151284   Reddit           Asia
24    2018-01-01 00:17:58  read  country_7  2458151285   Reddit         Africa
25    2018-01-01 00:18:55  read  country_2  2458151286  AdWords  North America
26    2018-01-01 00:20:18  read  country_5  2458151287      SEO  North America
27    2018-01-01 00:20:44  read  country_2  2458151288      SEO  North America
28    2018-01-01 00:23:16  read  country_2  2458151289   Reddit           Asia
29    2018-01-01 00:23:51  read  country_7  2458151290   Reddit           Asia
...                   ...   ...        ...         ...      ...            ...
1765  2018-01-01 23:41:11  read  country_2  2458153026   Reddit         Africa
1766  2018-01-01 23:41:51  read  country_5  2458153027  AdWords           Asia
1767  2018-01-01 23:43:54  read  country_5  2458153028  AdWords         Europe
1768  2018-01-01 23:44:52  read  country_8  2458153029   Reddit  South America
1769  2018-01-01 23:45:09  read  country_5  2458153030  AdWords      Australia
1770  2018-01-01 23:45:12  read  country_6  2458153031   Reddit           Asia
1771  2018-01-01 23:45:56  read  country_5  2458153032  AdWords         Africa
1772  2018-01-01 23:45:58  read  country_7  2458153033      SEO  South America
1773  2018-01-01 23:46:13  read  country_8  2458153034   Reddit           Asia
1774  2018-01-01 23:46:22  read  country_2  2458153035  AdWords           Asia
1775  2018-01-01 23:47:19  read  country_2  2458153036  AdWords           Asia
1776  2018-01-01 23:49:04  read  country_6  2458153037   Reddit           Asia
1777  2018-01-01 23:49:52  read  country_5  2458153038      SEO  North America
1778  2018-01-01 23:51:17  read  country_2  2458153039   Reddit           Asia
1779  2018-01-01 23:51:25  read  country_4  2458153040      SEO  South America
1780  2018-01-01 23:51:46  read  country_8  2458153041  AdWords         Africa
1781  2018-01-01 23:51:52  read  country_2  2458153042   Reddit           Asia
1782  2018-01-01 23:53:03  read  country_2  2458153043  AdWords           Asia
1783  2018-01-01 23:53:33  read  country_3  2458153044   Reddit           Asia
1784  2018-01-01 23:54:03  read  country_2  2458153045      SEO  North America
1785  2018-01-01 23:54:26  read  country_2  2458153046  AdWords         Africa
1786  2018-01-01 23:54:39  read  country_6  2458153047   Reddit           Asia
1787  2018-01-01 23:54:45  read  country_2  2458153048   Reddit           Asia
1788  2018-01-01 23:55:04  read  country_7  2458153049  AdWords         Europe
1789  2018-01-01 23:56:42  read  country_4  2458153050  AdWords           Asia
1790  2018-01-01 23:57:14  read  country_2  2458153051  AdWords  North America
1791  2018-01-01 23:58:33  read  country_8  2458153052      SEO           Asia
1792  2018-01-01 23:59:36  read  country_6  2458153053   Reddit           Asia
1793  2018-01-01 23:59:36  read  country_7  2458153054  AdWords         Europe
1794  2018-01-01 23:59:38  read  country_5  2458153055   Reddit           Asia

[1795 rows x 6 columns]

In [18]:
article_read.head(2)

           my_datetime event    country     user_id source          topic
0  2018-01-01 00:01:01  read  country_7  2458151261    SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262    SEO  South America

In [19]:
article_read.tail(2)

              my_datetime event    country     user_id   source   topic
1793  2018-01-01 23:59:36  read  country_7  2458153054  AdWords  Europe
1794  2018-01-01 23:59:38  read  country_5  2458153055   Reddit    Asia

In [21]:
article_read.sample(5)

              my_datetime event    country     user_id   source          topic
1709  2018-01-01 23:03:14  read  country_2  2458152970   Reddit         Africa
899   2018-01-01 12:07:02  read  country_7  2458152160      SEO  North America
142   2018-01-01 02:06:11  read  country_5  2458151403   Reddit           Asia
756   2018-01-01 10:09:20  read  country_7  2458152017   Reddit  South America
1351  2018-01-01 18:19:39  read  country_7  2458152612  AdWords           Asia

In [24]:
article_read[['country', 'source', 'event']]

        country   source event
0     country_7      SEO  read
1     country_7      SEO  read
2     country_7  AdWords  read
3     country_7  AdWords  read
4     country_8   Reddit  read
5     country_6   Reddit  read
6     country_2   Reddit  read
7     country_6  AdWords  read
8     country_7  AdWords  read
9     country_5   Reddit  read
10    country_5  AdWords  read
11    country_7      SEO  read
12    country_5   Reddit  read
13    country_2   Reddit  read
14    country_7   Reddit  read
15    country_7      SEO  read
16    country_8      SEO  read
17    country_2   Reddit  read
18    country_4      SEO  read
19    country_2   Reddit  read
20    country_2   Reddit  read
21    country_7   Reddit  read
22    country_2  AdWords  read
23    country_2   Reddit  read
24    country_7   Reddit  read
25    country_2  AdWords  read
26    country_5      SEO  read
27    country_2      SEO  read
28    country_2   Reddit  read
29    country_7   Reddit  read
...         ...      ...   ...
1765  country_2   Reddit  read
1766  country_5  AdWords  read
1767  country_5  AdWords  read
1768  country_8   Reddit  read
1769  country_5  AdWords  read
1770  country_6   Reddit  read
1771  country_5  AdWords  read
1772  country_7      SEO  read
1773  country_8   Reddit  read
1774  country_2  AdWords  read
1775  country_2  AdWords  read
1776  country_6   Reddit  read
1777  country_5      SEO  read
1778  country_2   Reddit  read
1779  country_4      SEO  read
1780  country_8  AdWords  read
1781  country_2   Reddit  read
1782  country_2  AdWords  read
1783  country_3   Reddit  read
1784  country_2      SEO  read
1785  country_2  AdWords  read
1786  country_6   Reddit  read
1787  country_2   Reddit  read
1788  country_7  AdWords  read
1789  country_4  AdWords  read
1790  country_2  AdWords  read
1791  country_8      SEO  read
1792  country_6   Reddit  read
1793  country_7  AdWords  read
1794  country_5   Reddit  read

[1795 rows x 3 columns]

In [27]:
article_read.country # print series instead of df

0       country_7
1       country_7
2       country_7
3       country_7
4       country_8
5       country_6
6       country_2
7       country_6
8       country_7
9       country_5
10      country_5
11      country_7
12      country_5
13      country_2
14      country_7
15      country_7
16      country_8
17      country_2
18      country_4
19      country_2
20      country_2
21      country_7
22      country_2
23      country_2
24      country_7
25      country_2
26      country_5
27      country_2
28      country_2
29      country_7
          ...
1765    country_2
1766    country_5
1767    country_5
1768    country_8
1769    country_5
1770    country_6
1771    country_5
1772    country_7
1773    country_8
1774    country_2
1775    country_2
1776    country_6
1777    country_5
1778    country_2
1779    country_4
1780    country_8
1781    country_2
1782    country_2
1783    country_3
1784    country_2
1785    country_2
1786    country_6
1787    country_2
1788    country_7
1789    country_4
1790    country_2
1791    country_8
1792    country_6
1793    country_7
1794    country_5
Name: country, Length: 1795, dtype: object

In [31]:
# filter for a value
article_read[article_read.source == 'SEO']
article_read[article_read['source'] == 'SEO']

              my_datetime event    country     user_id source          topic
0     2018-01-01 00:01:01  read  country_7  2458151261    SEO  North America
1     2018-01-01 00:03:20  read  country_7  2458151262    SEO  South America
11    2018-01-01 00:08:57  read  country_7  2458151272    SEO      Australia
15    2018-01-01 00:11:22  read  country_7  2458151276    SEO  North America
16    2018-01-01 00:13:05  read  country_8  2458151277    SEO  North America
18    2018-01-01 00:13:39  read  country_4  2458151279    SEO  North America
26    2018-01-01 00:20:18  read  country_5  2458151287    SEO  North America
27    2018-01-01 00:20:44  read  country_2  2458151288    SEO  North America
30    2018-01-01 00:24:52  read  country_6  2458151291    SEO  North America
41    2018-01-01 00:35:23  read  country_5  2458151302    SEO           Asia
54    2018-01-01 00:46:42  read  country_5  2458151315    SEO  North America
56    2018-01-01 00:49:37  read  country_7  2458151317    SEO  North America
57    2018-01-01 00:49:58  read  country_2  2458151318    SEO         Europe
60    2018-01-01 00:55:38  read  country_7  2458151321    SEO  North America
62    2018-01-01 00:56:27  read  country_6  2458151323    SEO           Asia
69    2018-01-01 01:03:19  read  country_5  2458151330    SEO         Europe
72    2018-01-01 01:04:22  read  country_8  2458151333    SEO  North America
73    2018-01-01 01:05:51  read  country_2  2458151334    SEO  North America
77    2018-01-01 01:12:51  read  country_4  2458151338    SEO         Africa
80    2018-01-01 01:14:24  read  country_4  2458151341    SEO         Africa
81    2018-01-01 01:15:53  read  country_7  2458151342    SEO  North America
83    2018-01-01 01:17:14  read  country_2  2458151344    SEO  South America
87    2018-01-01 01:18:12  read  country_6  2458151348    SEO      Australia
91    2018-01-01 01:20:37  read  country_7  2458151352    SEO  North America
97    2018-01-01 01:24:49  read  country_2  2458151358    SEO  North America
98    2018-01-01 01:28:30  read  country_4  2458151359    SEO           Asia
106   2018-01-01 01:35:40  read  country_5  2458151367    SEO  North America
110   2018-01-01 01:37:56  read  country_2  2458151371    SEO         Africa
114   2018-01-01 01:41:15  read  country_7  2458151375    SEO  North America
125   2018-01-01 01:51:51  read  country_2  2458151386    SEO  South America
...                   ...   ...        ...         ...    ...            ...
1601  2018-01-01 21:41:50  read  country_2  2458152862    SEO           Asia
1602  2018-01-01 21:44:00  read  country_5  2458152863    SEO  North America
1603  2018-01-01 21:44:10  read  country_5  2458152864    SEO  North America
1615  2018-01-01 21:52:25  read  country_8  2458152876    SEO  North America
1616  2018-01-01 21:52:31  read  country_4  2458152877    SEO         Europe
1619  2018-01-01 21:56:27  read  country_7  2458152880    SEO         Europe
1624  2018-01-01 21:59:03  read  country_8  2458152885    SEO  North America
1637  2018-01-01 22:07:57  read  country_2  2458152898    SEO      Australia
1641  2018-01-01 22:09:53  read  country_6  2458152902    SEO  North America
1662  2018-01-01 22:28:41  read  country_7  2458152923    SEO  North America
1664  2018-01-01 22:30:26  read  country_4  2458152925    SEO  North America
1669  2018-01-01 22:33:19  read  country_7  2458152930    SEO      Australia
1675  2018-01-01 22:43:25  read  country_5  2458152936    SEO           Asia
1688  2018-01-01 22:49:18  read  country_1  2458152949    SEO         Africa
1692  2018-01-01 22:52:44  read  country_2  2458152953    SEO  South America
1694  2018-01-01 22:53:19  read  country_2  2458152955    SEO  North America
1706  2018-01-01 23:01:15  read  country_7  2458152967    SEO  North America
1708  2018-01-01 23:03:12  read  country_6  2458152969    SEO         Europe
1723  2018-01-01 23:14:18  read  country_3  2458152984    SEO  North America
1736  2018-01-01 23:21:08  read  country_5  2458152997    SEO           Asia
1740  2018-01-01 23:23:20  read  country_7  2458153001    SEO           Asia
1748  2018-01-01 23:26:34  read  country_7  2458153009    SEO  South America
1756  2018-01-01 23:32:29  read  country_7  2458153017    SEO  North America
1757  2018-01-01 23:32:36  read  country_7  2458153018    SEO         Europe
1762  2018-01-01 23:36:09  read  country_5  2458153023    SEO  North America
1772  2018-01-01 23:45:58  read  country_7  2458153033    SEO  South America
1777  2018-01-01 23:49:52  read  country_5  2458153038    SEO  North America
1779  2018-01-01 23:51:25  read  country_4  2458153040    SEO  South America
1784  2018-01-01 23:54:03  read  country_2  2458153045    SEO  North America
1791  2018-01-01 23:58:33  read  country_8  2458153052    SEO           Asia

[346 rows x 6 columns]

In [33]:
article_read[article_read.country == 'country_2'][['user_id', 'topic', 'country']]

         user_id          topic    country
6     2458151267         Europe  country_2
13    2458151274         Europe  country_2
17    2458151278           Asia  country_2
19    2458151280           Asia  country_2
20    2458151281           Asia  country_2
22    2458151283         Europe  country_2
23    2458151284           Asia  country_2
25    2458151286  North America  country_2
27    2458151288  North America  country_2
28    2458151289           Asia  country_2
34    2458151295  North America  country_2
44    2458151305           Asia  country_2
48    2458151309           Asia  country_2
53    2458151314           Asia  country_2
57    2458151318         Europe  country_2
70    2458151331  South America  country_2
71    2458151332           Asia  country_2
73    2458151334  North America  country_2
82    2458151343         Africa  country_2
83    2458151344  South America  country_2
97    2458151358  North America  country_2
99    2458151360         Europe  country_2
107   2458151368           Asia  country_2
108   2458151369           Asia  country_2
110   2458151371         Africa  country_2
115   2458151376  North America  country_2
116   2458151377      Australia  country_2
117   2458151378           Asia  country_2
118   2458151379         Europe  country_2
121   2458151382  South America  country_2
...          ...            ...        ...
1692  2458152953  South America  country_2
1693  2458152954      Australia  country_2
1694  2458152955  North America  country_2
1699  2458152960  South America  country_2
1700  2458152961           Asia  country_2
1702  2458152963           Asia  country_2
1704  2458152965      Australia  country_2
1709  2458152970         Africa  country_2
1720  2458152981      Australia  country_2
1728  2458152989           Asia  country_2
1730  2458152991           Asia  country_2
1731  2458152992  South America  country_2
1738  2458152999           Asia  country_2
1743  2458153004  North America  country_2
1745  2458153006         Europe  country_2
1749  2458153010           Asia  country_2
1750  2458153011  South America  country_2
1754  2458153015  North America  country_2
1758  2458153019         Africa  country_2
1761  2458153022           Asia  country_2
1765  2458153026         Africa  country_2
1774  2458153035           Asia  country_2
1775  2458153036           Asia  country_2
1778  2458153039           Asia  country_2
1781  2458153042           Asia  country_2
1782  2458153043           Asia  country_2
1784  2458153045  North America  country_2
1785  2458153046         Africa  country_2
1787  2458153048           Asia  country_2
1790  2458153051  North America  country_2

[462 rows x 3 columns]